;Code generated by JETcompiler

declare i8*    @malloc(i32)
declare i8*    @calloc(i32, i32)
declare void   @free(i8*)
declare void   @printInt(i32)
declare void   @printDouble(double)
declare void   @printFloat(float)
declare void   @printString(i8*)
declare i32    @readInt()
declare double @readDouble()
declare float  @readFloat()

define i32 @main() {
;!!end function header
;!!begin FuncallOperatorExpr:
;!!begin UnaryMinus:
;!!begin IntegerLiteral:
%uid.1 = alloca i32
store i32 1, i32* %uid.1
;!!end IntegerLiteral:
%uid.2 = load i32* %uid.1
%uid.3 = alloca i32
%uid.4 = sub i32 0, %uid.2
store i32 %uid.4, i32* %uid.3
;!!end UnaryMinusExpr
%uid.0 = load i32* %uid.3
call void @printInt(i32 %uid.0)
;!!end FuncalOperatorExpr
;!!ReturnStmt:
;!!begin IntegerLiteral:
%uid.5 = alloca i32
store i32 0, i32* %uid.5
;!!end IntegerLiteral:
%uid.6 = load i32* %uid.5
ret i32 %uid.6
}
