;Code generated by JETcompiler

declare i8*    @malloc(i32)
declare i8*    @calloc(i32, i32)
declare void   @free(i8*)
declare void   @printInt(i32)
declare void   @printDouble(double)
declare void   @printFloat(float)
declare void   @printString(i8*)
declare i32    @readInt()
declare double @readDouble()
declare float  @readFloat()

define i32 @main() {
;!!end function header
;!!ReturnStmt:
;!!begin IntegerLiteral:
%uid.0 = alloca i32
store i32 0, i32* %uid.0
;!!end IntegerLiteral:
%uid.1 = load i32* %uid.0
ret i32 %uid.1
}
