;Code generated by JETcompiler

declare i8*    @malloc(i32)
declare i8*    @calloc(i32, i32)
declare void   @free(i8*)
declare void   @printInt(i32)
declare void   @printDouble(double)
declare void   @printFloat(float)
declare void   @printString(i8*)
declare i32    @readInt()
declare double @readDouble()
declare float  @readFloat()

define i32 @main() {
;!!end function header
;!!begin IntegerLiteral:
%uid.1 = alloca i32
store i32 7, i32* %uid.1
;!!end IntegerLiteral:
;!!begin DeclarationStmt, FieldValue != null
%uid.0 = alloca i32
%uid.2 = load i32* %uid.1
store i32 %uid.2, i32* %uid.0
;!!end DeclarationStmt
;!!begin FuncallOperatorExpr:
;!!begin and end of IdentifierExpr, passing "%uid.0" as "x"
%uid.3 = load i32* %uid.0
call void @printInt(i32 %uid.3)
;!!end FuncalOperatorExpr
;!!ReturnStmt:
;!!begin IntegerLiteral:
%uid.4 = alloca i32
store i32 0, i32* %uid.4
;!!end IntegerLiteral:
%uid.5 = load i32* %uid.4
ret i32 %uid.5
}
