;Code generated by JETcompiler

declare i8*    @malloc(i32)
declare i8*    @calloc(i32, i32)
declare void   @free(i8*)
declare void   @printInt(i32)
declare void   @printDouble(double)
declare void   @printFloat(float)
declare void   @printString(i8*)
declare i32    @readInt()
declare double @readDouble()
declare float  @readFloat()

define i32 @main() {
;!!end function header
;!!begin IntegerLiteral:
%uid.1 = alloca i32
store i32 17, i32* %uid.1
;!!end IntegerLiteral:
;!!begin DeclarationStmt, FieldValue != null
%uid.0 = alloca i32
%uid.2 = load i32* %uid.1
store i32 %uid.2, i32* %uid.0
;!!end DeclarationStmt
;!!begin WhileStmt:
br label %Label0LoopCond
Label0LoopCond:
;!!begin RelationExpr:
;!!begin and end of IdentifierExpr, passing "%uid.0" as "y"
%uid.3 = load i32* %uid.0
;!!begin IntegerLiteral:
%uid.5 = alloca i32
store i32 0, i32* %uid.5
;!!end IntegerLiteral:
%uid.4 = load i32* %uid.5
%uid.6 = icmp sgt i32 %uid.3, %uid.4
%uid.7 = alloca i1
store i1 %uid.6, i1* %uid.7
;!!end RelationExpr
%uid.8 = load i1* %uid.7
br i1 %uid.8, label %Label1LoopBody, label %Label2LoopEnd
Label1LoopBody:
;!!begin AssignmentExpr:
;!!begin AddExpr:
;!!begin and end of IdentifierExpr, passing "%uid.0" as "y"
%uid.9 = load i32* %uid.0
;!!begin IntegerLiteral:
%uid.11 = alloca i32
store i32 2, i32* %uid.11
;!!end IntegerLiteral:
%uid.10 = load i32* %uid.11
%uid.12 = sub i32 %uid.9, %uid.10
%uid.13 = alloca i32
store i32 %uid.12, i32* %uid.13
;!!end AddExpr:
;!!begin and end of IdentifierExpr, passing "%uid.0" as "y"
%uid.14 = load i32* %uid.13
store i32 %uid.14, i32* %uid.0
;!!end AssignmentExpr:
br label%Label0LoopCond
Label2LoopEnd:
;!!end WhileStmt
;!! IfteStmt
;!!begin RelationExpr:
;!!begin and end of IdentifierExpr, passing "%uid.0" as "y"
%uid.15 = load i32* %uid.0
;!!begin IntegerLiteral:
%uid.17 = alloca i32
store i32 0, i32* %uid.17
;!!end IntegerLiteral:
%uid.16 = load i32* %uid.17
%uid.18 = icmp slt i32 %uid.15, %uid.16
%uid.19 = alloca i1
store i1 %uid.18, i1* %uid.19
;!!end RelationExpr
%uid.20 = load i1* %uid.19
br i1 %uid.20, label %Label3IfteTrue, label %Label4IfteFalse
Label3IfteTrue:
;!!begin FuncallOperatorExpr:
;!!begin IntegerLiteral:
%uid.22 = alloca i32
store i32 0, i32* %uid.22
;!!end IntegerLiteral:
%uid.21 = load i32* %uid.22
call void @printInt(i32 %uid.21)
;!!end FuncalOperatorExpr
;!!ReturnStmt:
;!!begin IntegerLiteral:
%uid.23 = alloca i32
store i32 0, i32* %uid.23
;!!end IntegerLiteral:
%uid.24 = load i32* %uid.23
ret i32 %uid.24
br label %Label5IfteEnd
Label4IfteFalse:
;!!begin FuncallOperatorExpr:
;!!begin IntegerLiteral:
%uid.26 = alloca i32
store i32 1, i32* %uid.26
;!!end IntegerLiteral:
%uid.25 = load i32* %uid.26
call void @printInt(i32 %uid.25)
;!!end FuncalOperatorExpr
;!!ReturnStmt:
;!!begin IntegerLiteral:
%uid.27 = alloca i32
store i32 0, i32* %uid.27
;!!end IntegerLiteral:
%uid.28 = load i32* %uid.27
ret i32 %uid.28
br label %Label5IfteEnd
Label5IfteEnd:
;!!end ifte
}
